name: Kernel With Logs

on: push

jobs:
  build:
    name: My Job;
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build Kernel
      run: |
        chmod a+x ./build.sh
        chmod a+x ./log.sh
        ./log.sh
      shell: bash
      env:
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }} 
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }} 
